### PR TITLE
adds version check and optional self update in tlsx

### LINKED ISSUE #196: add update flags to tlsx
### Proposed Changes

```console
UPDATE:
   -up, -update                 update tlsx to the latest version
   -duc, -disable-update-check  disable automatic update check
```

### Reference
https://github.com/projectdiscovery/pdtm/blob/87dc669d40186e990c988c5a0ee3940302814b8c/examples/main.go#L16-L32

### PR DESCRIPTION
**Pull request by RamanaReddy0M**
### Proposed Changes

- adds update flags
```console
UPDATE:
   -up, -update                 update tlsx to latest version
   -duc, -disable-update-check  disable automatic tlsx update check

```
- update and version check is implemented in https://github.com/projectdiscovery/utils/pull/101 instead of pdtm since we can directly use `utils/update` in pdtm (https://github.com/projectdiscovery/pdtm/issues/69)
- when upgrading version release notes are printed 

closes #196

### CODE REVIEW

**Comment by tarunKoyalwar** [comment]
## version check

```console
$ ./tlsx -u scanme.sh
  

  _____ _    _____  __
 |_   _| |  / __\ \/ /
   | | | |__\__ \>  < 
   |_| |____|___/_/\_\	v1.0.5

		projectdiscovery.io

[INF] Current tlsx version v1.0.5 (latest)
scanme.sh:443
[INF] Connections made using crypto/tls: 1, zcrypto/tls: 0, openssl: 0

```

### Failed test cases
```console
$  HTTPS_PROXY=127.0.0.1:8080 go run . -u scanme.sh  
  

  _____ _    _____  __
 |_   _| |  / __\ \/ /
   | | | |__\__ \>  < 
   |_| |____|___/_/\_\	v1.0.4

		projectdiscovery.io

[ERR] tlsx version check failed
scanme.sh:443
[INF] Connections made using crypto/tls: 1, zcrypto/tls: 0, openssl: 0
```
- version check error is only shown in verbose mode
```console
$ HTTPS_PROXY=127.0.0.1:8080 go run . -u scanme.sh -v
  

  _____ _    _____  __
 |_   _| |  / __\ \/ /
   | | | |__\__ \>  < 
   |_| |____|___/_/\_\	v1.0.4

		projectdiscovery.io

[ERR] tlsx version check failed [updater:RUNTIME] failed to get response body of GET https://api.pdtm.sh/api/v1/tools/tlsx?arch=arm64&go_version=go1.20.2&os=darwin <- remote error: tls: user canceled
[INF] Processing input scanme.sh:443
scanme.sh:443
[INF] Connections made using crypto/tls: 1, zcrypto/tls: 0, openssl: 0

```

### Anything else
- certificate validation is skipped for version check but not when updating binary

**Comment by tarunKoyalwar** [comment]
### update with release notes

- to simulate this testcase clone and change version in `runner/banner.go` to `v1.0.4`

```console
$ ./tlsx -up
  

  _____ _    _____  __
 |_   _| |  / __\ \/ /
   | | | |__\__ \>  < 
   |_| |____|___/_/\_\	v1.0.4

		projectdiscovery.io

7.17 MiB / 7.17 MiB [--------------------------------------------------------] 100.00% 13.51 MiB p/s

[INF] tlsx sucessfully updated 1.0.4 -> 1.0.5 (latest)

  ## What's Changed                                                           
                                                                              
  • Fixed cipher enumration bug and improvements by @tarunKoyalwar in         
  https://github.com/projectdiscovery/tlsx/pull/168                           
  • Fixed errorutil import by @tarunKoyalwar in                               
  https://github.com/projectdiscovery/tlsx/pull/162                           
  • Fixed example tests and more by @tarunKoyalwar in                         
  https://github.com/projectdiscovery/tlsx/pull/163                           
  • Fixed bug with  -revoke  option and added  -hardfail  option by           
  @tarunKoyalwar in https://github.com/projectdiscovery/tlsx/pull/171         
  • Added support for healtcheck ( -hc ) option by @Mzack9999 in              
  https://github.com/projectdiscovery/tlsx/pull/173                           
                                                                              
  ## New Contributors                                                         
                                                                              
  • @noraj made their first contribution in                                   
  https://github.com/projectdiscovery/tlsx/pull/165                           
                                                                              
  Full Changelog:                                                             
  https://github.com/projectdiscovery/tlsx/compare/v1.0.4...v1.0.5            


```

Screenshot 2023-03-12 at 8 52 53 PM

### failed testcase
- fails since ceritifcates are validated  while updating binary
```console
HTTPS_PROXY=127.0.0.1:8080 go run . -update        
  

  _____ _    _____  __
 |_   _| |  / __\ \/ /
   | | | |__\__ \>  < 
   |_| |____|___/_/\_\	v1.0.4

		projectdiscovery.io

[updater] failed to fetch latest release of tlsx
exit status 1

```

**Review by ehsandeep — APPROVED** [review]
```console
./tlsx -up
  

  _____ _    _____  __
 |_   _| |  / __\ \/ /
   | | | |__\__ \>  < 
   |_| |____|___/_/\_\	v1.0.4

		projectdiscovery.io

7.17 MiB / 7.17 MiB [---------------------------------------------------------] 100.00% 2.29 MiB p/s

[INF] tlsx sucessfully updated 1.0.4 -> 1.0.5 (latest)

  ## What's Changed                                                           
                                                                              
  • Fixed cipher enumration bug and improvements by @tarunKoyalwar in         
  https://github.com/projectdiscovery/tlsx/pull/168                           
  • Fixed errorutil import by @tarunKoyalwar in                               
  https://github.com/projectdiscovery/tlsx/pull/162                           
  • Fixed example tests and more by @tarunKoyalwar in                         
  https://github.com/projectdiscovery/tlsx/pull/163                           
  • Fixed bug with  -revoke  option and added  -hardfail  option by           
  @tarunKoyalwar in https://github.com/projectdiscovery/tlsx/pull/171         
  • Added support for healtcheck ( -hc ) option by @Mzack9999 in              
  https://github.com/projectdiscovery/tlsx/pull/173                           
                                                                              
  ## New Contributors                                                         
                                                                              
  • @noraj made their first contribution in                                   
  https://github.com/projectdiscovery/tlsx/pull/165      
  ```

**Review by Mzack9999 — APPROVED** [review]
lgtm!

**Pull request merged**
