### PR TITLE
use one time pool for cipher enum

### LINKED ISSUE #327: Use onetimepool for cipher enumeration
### Please describe your feature request:

- use connpool.OneTimePool to generate a conn pool and use those for cipher enumeration

### Describe the use case of this feature:

- this makes cipher enumeration 2x faster

### PR DESCRIPTION
**Pull request by tarunKoyalwar**
### Proposed Changes

- use one time pool of connections during cipher enumeration
- closes #327 

## Before

```console
$ cmdutil tlsx -u scanme.sh -ce -sm ztls
  

  _____ _    _____  __
 |_   _| |  / __\ \/ /
   | | | |__\__ \>  < 
   |_| |____|___/_/\_\	v1.1.3

		projectdiscovery.io

[INF] Current tlsx version v1.1.3 (latest)
[INF] Started TLS Cipher Enumeration using ztls mode
scanme.sh:443 [tls12] [TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256]
scanme.sh:443 [tls10] [TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA]
scanme.sh:443 [tls11] [TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA]

------------------------------
Command: tlsx -u scanme.sh -ce -sm ztls
Max RSS: 41 MB
Sys Time: 105.118µs
User Time: 150.007µs
Actual Time: 2m30.26040875s
Voluntary Context Switch (nvcsw): 46
```

## After

```console
$ cmdutil ./tlsx -u scanme.sh -ce -sm ztls -cec 10
  

  _____ _    _____  __
 |_   _| |  / __\ \/ /
   | | | |__\__ \>  < 
   |_| |____|___/_/\_\	v1.1.3

		projectdiscovery.io

[INF] Current tlsx version v1.1.3 (latest)
[INF] Started TLS Cipher Enumeration using ztls mode
scanme.sh:443 [tls12] [TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256]
scanme.sh:443 [tls10] [TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA]
scanme.sh:443 [tls11] [TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA]

------------------------------
Command: ./tlsx -u scanme.sh -ce -sm ztls -cec 10
Max RSS: 47 MB
Sys Time: 119.452µs
User Time: 176.263µs
Actual Time: 1m17.916825s
Voluntary Context Switch (nvcsw): 52

```

### CODE REVIEW

**Review by Mzack9999 — CHANGES_REQUESTED** [review]
implementation: lgtm!

Marking with `requested changes` as I think we can reuse `github.com/projectdiscovery/utils/conn/connpool/onetimepool.go` and reduce code redundancy

**Review by Mzack9999 — APPROVED** [review]
lgtm - I'm getting some strange context canceled error, even if the one used was `context.Background(...)`

```console
$ go run . -u scanme.sh -ce -sm ztls -cec 10 -verbose
  

  _____ _    _____  __
 |_   _| |  / __\ \/ /
   | | | |__\__ \>  < 
   |_| |____|___/_/\_\  v1.1.3

                projectdiscovery.io

[INF] Current tlsx version v1.1.3 (latest)
[INF] Processing input scanme.sh:443
[INF] Started TLS Cipher Enumeration using ztls mode
[ztls] Starting cipher enumeration with 345 ciphers in tls12
[ztls] Starting cipher enumeration with 345 ciphers in tls10
[ERR] tlsx: ztls: failed to run connection pool: context canceled
[ztls] Starting cipher enumeration with 345 ciphers in tls11
[ERR] tlsx: ztls: failed to run connection pool: context canceled
scanme.sh:443 [tls12] [TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256]
scanme.sh:443 [tls10] [TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA]
scanme.sh:443 [tls11] [TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA]
```
Not sure if somehow the `.Stop(...)` method might overlap with `Acquire(...)`

**Comment by tarunKoyalwar** [comment]
- context cancelled error is now hidden since it is expected due to `.Close()`
```console
$ go run . -u scanme.sh -ce -sm ztls -cec 10 -verbose
  

  _____ _    _____  __
 |_   _| |  / __\ \/ /
   | | | |__\__ \>  < 
   |_| |____|___/_/\_\	v1.1.3

		projectdiscovery.io

[INF] Current tlsx version v1.1.3 (latest)
[INF] Processing input scanme.sh:443
[INF] Started TLS Cipher Enumeration using ztls mode
[ztls] Starting cipher enumeration with 345 ciphers in tls12
[ztls] Starting cipher enumeration with 345 ciphers in tls10
[ztls] Starting cipher enumeration with 345 ciphers in tls11
scanme.sh:443 [tls12] [TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384]
scanme.sh:443 [tls10] [TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA]
scanme.sh:443 [tls11] [TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA]
```

**Review by Mzack9999 — APPROVED** [review]
lgtm!
Screenshot 2023-08-23 at 23 34 53

**Review by ehsandeep — APPROVED** [review]

**Pull request merged**
